### PR TITLE
subviews: fix for properly clearing render targets in some cases

### LINKED ISSUE #410: [subviews] Cursor sprite collecting garbage
This is a problem I just discovered on Linux - I'm pretty sure it wasn't there some time ago. Anyway, it's specific to subviews, my Linux computer and SDL2.

After moving the cursor around a bit, it starts to look like this.

cursor

I try to bisect it later.

### PR DESCRIPTION
**Pull request by MarcelHB**
I removed your other change since there is no reason IMO to keep that switch - and it did not help here.

closes #410

### CODE REVIEW

File: gemrb/plugins/SDLVideo/SDL20Video.cpp [hunk 1]
```diff
@@ -126,14 +126,7 @@ int SDL20VideoDriver::UpdateRenderTarget(const Color* color)
 		return ret;
 	}
 
-	if (screenClip.Dimensions() == screenSize)
```
Comment (bradallred) [inline gemrb/plugins/SDLVideo/SDL20Video.cpp]: we actually need this to silence complaints from the Metal backend. It too might just be an SDL bug for all I know, but debug builds of the renderer will assert without this under the current SDL 2.0.10 at least.

Comment (MarcelHB) [reply gemrb/plugins/SDLVideo/SDL20Video.cpp]: Argh, ok

Comment (MarcelHB) [reply gemrb/plugins/SDLVideo/SDL20Video.cpp]: I rephrase the comment in a way non-metal readers understand. :wink:

**Comment by MarcelHB** [comment]
Restored your fix.

**Comment by bradallred** [comment]
thanks!
