### PR TITLE
Palettes, shadows and blending

### LINKED ISSUE #2150: Non-accelerated blending broken
#### Bug description

The non-accelerated SDL2 version of blending got worse over time. While somewhat OK at v0.9.1, first drawbacks at v0.9.2, v0.9.3 can be considered broken.

It's tested on both D3D and OpenGL. Also not an SDL problem since all tests were done with SDL v2.30.

#### Screenshots
v0.9.1
blending_091

v0.9.2
blending_092

v0.9.3
blending_093

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.3
- [x] 0.9.2
- [ ] 0.9.1

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `OPENGL_BACKEND` enabled
- [x] SDL2 without `OPENGL_BACKEND` enabled

### PR DESCRIPTION
**Pull request by MarcelHB**
## Description
This fixes #2150, #2146 (and fallout) and also restores, again, infravision.

What does it do:
* Changes to `Palette` won't go unnoticed anymore which makes it easier to check if it needs to be updated to the surface.
* `SDLSurfaceSprite2D` has some easier to understand update-requirements for both palettes and surface.
* I've eliminated one manual blitting path, because I don't see where SDL2 is unable to do the same, so only one surface left to have.
* There is now an original palette + a tinted one when required, leaving the original untouched for rendering.
* Non-accelerated stencilling preserves the desired blend mode, so all code-paths look the same.

Tested all the known edge cases that now are easy to handle under less heuristics and state:
* PST: crystal room + Ignus spells
* IWD: Cloack of oscillating colors
* BG: Thalantyr's store room
* IWD2: infravision

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [x] I extended the documentation, if necessary
- [x] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

File: gemrb/core/CharAnimations.cpp [hunk 1]
```diff
@@ -2801,6 +2801,8 @@ void CharAnimations::PulseRGBModifiers()
 
 static inline void applyMod(const Color& src, Color& dest, const RGBModifier& mod) noexcept
 {
+	dest.a = 0xFF;
```
Comment (lynxlynxlynx) [inline gemrb/core/CharAnimations.cpp:2804]: I guess this is just from the default init of Color? It'd be better if we fixed this at the source.
I see `BMPImporter::GetPalette`, PNGImporter and PVRZImporter already handle it properly, just BAMImporter is missing the same signature, since it's not an ImgMgr. But it has code in `BAMImporter::Import` that should take care of it — is the v2 alpha detection at the end failing us?

Comment (MarcelHB) [reply gemrb/core/CharAnimations.cpp:2804]: The default init hasn't bothered be in this case, at least I'm not aware of one. It's this here: https://github.com/gemrb/gemrb/blob/f22f8625ee7676d4a8c32e6091534cbd782ee557/gemrb/plugins/FXOpcodes/FXOpcodes.cpp#L1351

File: gemrb/core/MurmurHash.h [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+* GNU General Public License for more details.
+*
+* You should have received a copy of the GNU General Public License
+* along with this program; if not, write to the Free Software
+* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
+*
+*/
+
+#ifndef H_GEMRB_MURMUR_HASH
+#define H_GEMRB_MURMUR_HASH
```
Comment (lynxlynxlynx) [inline gemrb/core/MurmurHash.h:21]: What's the benefit over using our existing hashing capabilities, std?

File: gemrb/plugins/AREImporter/AREImporter.cpp [hunk 3]
```diff
@@ -262,7 +262,7 @@ static TileProps MakeTileProps(const TileMap* tm, const ResRef& wedref, bool day
 		}
 		
 		if (hmit.clip.PointInside(pos)) {
-			b = hmpal->col[*hmit].r; // pick any channel, they are all the same
+			b = hmpal->operator[](*hmit).r; // pick any channel, they are all the same
```
Comment (lynxlynxlynx) [inline gemrb/plugins/AREImporter/AREImporter.cpp:265]: Can you add a GetColorAt or somesuch getter, so all these accesses will look a bit cleaner?

File: gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp [hunk 4]
```diff
@@ -103,27 +94,14 @@ void* SDLSurfaceSprite2D::LockSprite()
...
-{
-	// a 'version' implies tha palette was color modified
-	// however, the only caller her is RenderWithFlags
-	// where we already compare the version with the requested one
-	// the version includes the color modification so for now we dont worry about it
-	
-	const Holder<Palette>& pal = format.palette;
-	assert(pal);
-	return pal->GetVersion() != palVersion;
+	invalidate();
```
Comment (lynxlynxlynx) [inline gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp:100]: Why lowercase?

File: gemrb/core/MurmurHash.h (hunk 2 above)
Comment (MarcelHB) [reply gemrb/core/MurmurHash.h:21]: std needs a specialization for this case, as far as I see, and thus some implementation. And since I'm no hashing export, this one is safe and fast to use for streaming 4-bytes.

File: gemrb/plugins/AREImporter/AREImporter.cpp (hunk 3 above)
Comment (MarcelHB) [reply gemrb/plugins/AREImporter/AREImporter.cpp:265]: Sure.

File: gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp (hunk 4 above)
Comment (MarcelHB) [reply gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp:100]: Wasn't there some kind of private-vs-public kind of convention in some classes? Anyway, I can change it.

File: gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp [hunk 5]
```diff
@@ -188,97 +167,122 @@ bool SDLSurfaceSprite2D::ConvertFormatTo(const PixelFormat& tofmt) noexcept
...
+	return format.palette && palVersion != format.palette->GetVersion();
 }
 
-void* SDLSurfaceSprite2D::NewVersion(version_t newversion) const noexcept
+bool SDLSurfaceSprite2D::needToReshade(const Color* tint, BlitFlags flags) const noexcept {
+	return flags != appliedBlitFlags
+		|| ((flags & BlitFlags::COLOR_MOD) && tint && (appliedTint.Packed() & 0xFFFFFF00) != (tint->Packed() & 0xFFFFFF00))
+		|| ((flags & BlitFlags::ALPHA_MOD) && tint && (appliedTint.Packed() & 0xFF) != (tint->Packed() & 0xFF))
+		|| needToUpdatePalette()
+		|| surfaceInvalidated;
```
Comment (lynxlynxlynx) [inline gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp:209]: This could be checked sooner, for a tiny speed increase.

Comment (MarcelHB) [reply gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp:209]: Sure, why not

File: gemrb/tests/core/Test_Palette.cpp [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+	auto v3 = unit.GetVersion();
+	EXPECT_NE(v2a, v3);
+
+	unit.SetColor(0, c);
+	auto v4 = unit.GetVersion();
+	EXPECT_NE(v3, v4);
+}
+
+TEST(Palette_Test, CopyColors_Version) {
+Palette::Colors buffer;
```
Comment (lynxlynxlynx) [inline gemrb/tests/core/Test_Palette.cpp:62]: misaligned

**Comment by lynxlynxlynx** [comment]
Very nice, will have to recheck if it helps with #897 as well.

File: gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp (hunk 4 above)
Comment (lynxlynxlynx) [reply gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp:100]: In some few, mostly in imported code, but definitely not for most. I think it would be better to unify rather than making it more diverse. The one valid exception are iterator accessors, for obvious reasons.

File: gemrb/core/MurmurHash.h (hunk 2 above)
Comment (lynxlynxlynx) [reply gemrb/core/MurmurHash.h:21]: Did you forget to commit something? I don't see it actually being used anywhere.

File: gemrb/core/CharAnimations.cpp (hunk 1 above)
Comment (lynxlynxlynx) [reply gemrb/core/CharAnimations.cpp:2804]: These two opcodes [never pass an alpha](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op8), so we can fix it in them. I suggest either doing it manually or by adding a  Color::FromBGR, where we force the alpha. There's several other calls that pass a custom Color that need to be updated.

Comment (MarcelHB) [reply gemrb/core/CharAnimations.cpp:2804]: Ok, I'll take the `FromBGR` idea.

Comment (MarcelHB) [reply gemrb/core/CharAnimations.cpp]: I guess you meant all 4 methods on 0x8 and 0x9, right?

Comment (lynxlynxlynx) [reply gemrb/core/CharAnimations.cpp]: Yeah, those are fine, but aren't the other SetColorMod calls problematic too? I don't see anyone setting a non-zero alpha.

Comment (MarcelHB) [reply gemrb/core/CharAnimations.cpp]: This way I doesn't even work for my known case any more... Something eats the opaque value between opcode and `applyMod`.

Comment (lynxlynxlynx) [reply gemrb/core/CharAnimations.cpp]: It's not some other call resetting it to its value?

Comment (MarcelHB) [reply gemrb/core/CharAnimations.cpp]: At a second thought, I think the initial idea is better and the 2nd approach is fruitless: This `applyMod` isn't designed to work on any alpha value. Instead, it takes the original RGB, applies some mod and sets the destination's RGB. And yes, by any default init. of `Color`, alpha is 0, so is the palette's setup buffer.

So in my view, `applyMod` is the place to mark these colors as opaque.

Comment (lynxlynxlynx) [reply gemrb/core/CharAnimations.cpp]: It feels like an unnecessary side effect, since `dest` is passed by reference. `GlobalColorMod` does not use alpha, so you could fix its `rgb` member instead, it's just 4 places.

Comment (MarcelHB) [reply gemrb/core/CharAnimations.cpp]: That doesn't fix this since it is not copied on all code paths, on some it's just source.rgb x mod.rgb -> dest.rgb. So either we set dest.a = 0xFF (as initially) inside of `applyMod`, or we set buffer.a = dest.a = 0xFF outside of `applyMod`, or we change the color init., but I'm not sure about the impact by this.

Comment (MarcelHB) [reply gemrb/core/CharAnimations.cpp]: Or buffer.a = dest.a = src.a

Comment (MarcelHB) [reply gemrb/core/CharAnimations.cpp]: That's good we rule out unexpected side effects but also don't have to rewrite things or do another set-alpha-run.

Comment (lynxlynxlynx) [reply gemrb/core/CharAnimations.cpp]: What other case does that (I admit I forgot the one ColorMods.rgb setter in the same function)?

Comment (MarcelHB) [reply gemrb/core/CharAnimations.cpp]: Look at everything in `applyMod` that does not end in `dest = src;`: you will only see color modifications. So if `dest.a` is blank, it will remain regardless of source.a and modifier.a.
