### PR TITLE
GameControl: Implement smooth keyboard scrolling

### LINKED ISSUE #2316: BG2EE: Scrolling using arrow keys
#### Bug description
Scrolling on the game screen using the arrow keys causes the screen to "jump"/scroll with a lag, instead of being smooth.

Scrolling diagonally using arrow keys not working.

Scrolling by moving the cursor to the edge of the game screen/window works normally.

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [x] 0.9.4
- [ ] 0.9.3
- [ ] 0.9.2

### PR DESCRIPTION
**Pull request by CalamariDetective**
## Description
This resolves #2316. Previous behavior is that on pressing an arrow key the viewport would jump in the direction of the arrow key, repeating if key was held down. Diagonal key scrolling did not work. This commit changes to a smooth scroll with diagonal support that matches original IE behavior. Tested with IWD2 and PST.

This is my first PR ever, so any feedback is appreciated. Thanks!

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [ ] I extended the documentation, if necessary
- [x] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Thanks, will take a look!

File: gemrb/core/GUI/GameControl.cpp [hunk 1]
```diff
@@ -1117,6 +1132,24 @@ bool GameControl::OnKeyRelease(const KeyboardEvent& Key, unsigned short Mod)
...
+		case GEM_UP:
+		case GEM_DOWN:
+		case GEM_LEFT:
+		case GEM_RIGHT:
+			{
+				unsigned int releasedKey = 1 << (Key.keycode - GEM_LEFT);
+				scrollKeysDown &= ~releasedKey;
+				scrollKeysActive &= ~releasedKey;
+
+				// If the opposite arrow key is still held down, switch to that direction:
```
Comment (lynxlynxlynx) [inline gemrb/core/GUI/GameControl.cpp:1144]: Why is this needed, won't the next OnKeyPress set it properly?

File: gemrb/core/GUI/GameControl.cpp [hunk 2]
```diff
@@ -1117,6 +1132,24 @@ bool GameControl::OnKeyRelease(const KeyboardEvent& Key, unsigned short Mod)
...
+				unsigned int oppositeKey = releasedKey & 1 ? releasedKey << 1 : releasedKey >> 1;
+				if (scrollKeysDown & oppositeKey) {
+					scrollKeysActive |= oppositeKey;
+				}
+
+				ApplyKeyScrolling();
```
Comment (lynxlynxlynx) [inline gemrb/core/GUI/GameControl.cpp:1150]: This looks redundant, we should scroll on either press or release. In general, the originals did it on press, but I don't remember if I checked scrolling (#1849).

Comment (CalamariDetective) [reply gemrb/core/GUI/GameControl.cpp:1150]: I just checked PST: if you hold left and press right, it will scroll left then right. If you let go of right it will scroll left again. If you hold right, then press left, it ignores the left key and keeps scrolling right. Right overrides left and down overrides up. Releasing down/right makes it scroll up/left if they are still held. Not sure if they're doing down/up events or just checking the key press state of those keys each tick.

File: gemrb/core/GUI/GameControl.cpp (hunk 1 above)
Comment (CalamariDetective) [reply gemrb/core/GUI/GameControl.cpp:1144]: You only get repeat OnKeyPress events for the last key pressed. So, for example, if you press left and up, you'll get one event for left and repeated events for up. If you release up and keep left held down, you don't get any OnKeyPress events for left anymore.

File: gemrb/core/GUI/GameControl.cpp (hunk 2 above)
Comment (lynxlynxlynx) [reply gemrb/core/GUI/GameControl.cpp:1150]: So the oppositeKey stuff should be enough, we don't need to call ApplyKeyScrolling, right?

Comment (CalamariDetective) [reply gemrb/core/GUI/GameControl.cpp:1155]: ApplyKeyScrolling updates vpVector to match the keys that are currently pressed, so it needs to be called in OnKeyPress to start scrolling in a direction, and in OnKeyRelease to stop scrolling in that direction. I added some comments to clarify this.

Regarding the discussion on not relying on OnKeyRelease because another window might open:  in the initial coding I did find that OnKeyRelease isn't received if another window opens (for example, pressing "i" to open the inventory while scrolling). I addressed that in WillDraw: if key scrolling is active it stops scrolling if IsReceivingEvents() is false.

**Comment by lynxlynxlynx** [comment]
Thanks!
